// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KVF2wj5ltvtzuKNxXc9-EA4dOGGCsBM',
    appId: '1:498050735837:web:5a44557a54de0a93e5c534',
    messagingSenderId: '498050735837',
    projectId: 'claimvision-b0f20',
    authDomain: 'claimvision-b0f20.firebaseapp.com',
    storageBucket: 'claimvision-b0f20.firebasestorage.app',
    measurementId: 'G-SKP9RV3ME3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevh42_f8iIQMo5bNhkhKMgfw5PadS_KM',
    appId: '1:498050735837:android:23d1ca53685a3308e5c534',
    messagingSenderId: '498050735837',
    projectId: 'claimvision-b0f20',
    storageBucket: 'claimvision-b0f20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_L30XOVOH7ZnR0ujaOb6Dv41s5pxvu9k',
    appId: '1:498050735837:ios:a6b7411ad457e94de5c534',
    messagingSenderId: '498050735837',
    projectId: 'claimvision-b0f20',
    storageBucket: 'claimvision-b0f20.firebasestorage.app',
    iosBundleId: 'com.example.claimvision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_L30XOVOH7ZnR0ujaOb6Dv41s5pxvu9k',
    appId: '1:498050735837:ios:a6b7411ad457e94de5c534',
    messagingSenderId: '498050735837',
    projectId: 'claimvision-b0f20',
    storageBucket: 'claimvision-b0f20.firebasestorage.app',
    iosBundleId: 'com.example.claimvision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2KVF2wj5ltvtzuKNxXc9-EA4dOGGCsBM',
    appId: '1:498050735837:web:202e07d61a5d7287e5c534',
    messagingSenderId: '498050735837',
    projectId: 'claimvision-b0f20',
    authDomain: 'claimvision-b0f20.firebaseapp.com',
    storageBucket: 'claimvision-b0f20.firebasestorage.app',
    measurementId: 'G-WRQVM1FGX3',
  );
}
